=== AndresMoros/ifcd0210-andres-moros/module 002/ejercicios/2025-05-05/050525 - XSD 3/Ejercicio 1/libreria.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="libreria">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="libro" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="titulo"/>
                            <xs:element name="autor" maxOccurs="unbounded"/>
                            <xs:element name="genero" maxOccurs="unbounded"/>
                            <xs:element name="fecha-publicacion"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="titulo">
        <xs:simpleType>
            <xs:restriction base="xs:string">
                <xs:maxLength value="50"/>
            </xs:restriction>
        </xs:simpleType>
    </xs:element>

    <xs:element name="autor">
        <xs:simpleType>
            <xs:restriction base="xs:string">
                <xs:maxLength value="30"/>
            </xs:restriction>
        </xs:simpleType>
    </xs:element>

    <xs:element name="genero">
        <xs:simpleType>
            <xs:restriction base="xs:string">
                <xs:maxLength value="20"/>
            </xs:restriction>
        </xs:simpleType>
    </xs:element>

    <xs:element name="fecha-publicacion">
        <xs:simpleType>
            <xs:restriction base="xs:integer">
                <xs:minInclusive value="0" />
                <xs:maxInclusive value="2025" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>
</xs:schema>

=== AndresMoros/ifcd0210-andres-moros/module 002/ejercicios/2025-05-05/050525 - XSD 3/Ejercicio 1/libreria.xml
<?xml version="1.0" encoding="UTF-8"?>
<libreria xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="libreria.xsd">
    <libro>
        <titulo>El Festival de la Blasfemia</titulo>
        <autor>Angel David Revilla</autor>
        <genero>Horror</genero>
        <fecha-publicacion>2025</fecha-publicacion>
    </libro>
    <libro>
        <titulo>Christine</titulo>
        <autor>Stephen King</autor>
        <genero>Horror</genero>
        <fecha-publicacion>1983</fecha-publicacion>
    </libro>
    <libro>
        <titulo>Cuéntame tus sueños</titulo>
        <autor>Sidney Sheldon</autor>
        <genero>Novela</genero>
        <fecha-publicacion>1999</fecha-publicacion>
    </libro>
    <libro>
        <titulo>El Psicoanalista</titulo>
        <autor>John Katzenbach</autor>
        <genero>Thriller</genero>
        <fecha-publicacion>2003</fecha-publicacion>
    </libro>
    <libro>
        <titulo>La chica del tren</titulo>
        <autor>Paula Hawkins</autor>
        <genero>Suspenso</genero>
        <genero>Novela</genero>
        <fecha-publicacion>2016</fecha-publicacion>
    </libro>
</libreria>
