=== AndresMoros/ifcd0210-andres-moros/module 002/test 003/ANDRES DE JESUS MOROS ARAUJO/Ejercicio 1 y 2/morosos.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="morosos">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="vecino" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>

                            <xs:element name="registro" type="xs:positiveInteger" />

                            <xs:element name="nombre">
                                <xs:complexType>
                                    <xs:simpleContent>
                                        <xs:extension base="xs:string">
                                            <xs:attribute name="estado">
                                                <xs:simpleType>
                                                    <xs:restriction base="xs:string">
                                                        <xs:pattern value="Desempleado|Trabajador|Estudiante"></xs:pattern>
                                                    </xs:restriction>
                                                </xs:simpleType>    
                                            </xs:attribute>
                                        </xs:extension>
                                    </xs:simpleContent>
                                </xs:complexType>
                            </xs:element>

                            <xs:element name="direccion" type="xs:string"/>

                            <xs:element name="cantidad" type="xs:double"/>

                            <xs:element name="fecha">
                                <xs:simpleType>
                                    <xs:restriction base="xs:date">
                                        <xs:minInclusive value="2024-01-01"></xs:minInclusive>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>

                            <xs:element name="concepto-debido">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:pattern value="Ascensor|Piscina|Comunidad"></xs:pattern>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== AndresMoros/ifcd0210-andres-moros/module 002/test 003/ANDRES DE JESUS MOROS ARAUJO/Ejercicio 1 y 2/morosos.xml
<?xml version="1.0" encoding="UTF-8"?>

<morosos 
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="morosos.xsd">

    <vecino>
        <registro>1</registro>
        <nombre estado="Desempleado">Antonio</nombre>
        <direccion>C/ Ori√≥n, 10 5 A</direccion>
        <cantidad>220.50</cantidad>
        <fecha>2024-08-01</fecha>
        <concepto-debido>Piscina</concepto-debido>
    </vecino>

    <vecino>
        <registro>2</registro>
        <nombre estado="Trabajador">Eva</nombre>
        <direccion>C/ Sirio, 24 2 D</direccion>
        <cantidad>140.00</cantidad>
        <fecha>2024-07-01</fecha>
        <concepto-debido>Comunidad</concepto-debido>
    </vecino>

    <vecino>
        <registro>3</registro>
        <nombre estado="Estudiante">Juan</nombre>
        <direccion>C/ Bellatrix, 32 6 A</direccion>
        <cantidad>180.40</cantidad>
        <fecha>2024-08-01</fecha>
        <concepto-debido>Piscina</concepto-debido>
    </vecino>

    <vecino>
        <registro>4</registro>
        <nombre estado="Trabajador">Rosa</nombre>
        <direccion>C/ Vega, 14 2 C</direccion>
        <cantidad>200.00</cantidad>
        <fecha>2024-07-01</fecha>
        <concepto-debido>Piscina</concepto-debido>
    </vecino>

    <vecino>
        <registro>5</registro>
        <nombre estado="Estudiante">Luis Miguel</nombre>
        <direccion>C/ Deneb, 37 1 D</direccion>
        <cantidad>84.90</cantidad>
        <fecha>2024-07-01</fecha>
        <concepto-debido>Ascensor</concepto-debido>
    </vecino>
</morosos>
